package com.gamesuite.games.wordgames.crossword

/**
 * Crossword answers need real clues, and the bundled dictionary has no clue
 * data — so unlike word search (which can pull arbitrary dictionary words),
 * crossword uses small hand-authored, themed clue banks instead of trying
 * to auto-generate clues for random words.
 *
 * Upgrade pass (README item 9l) added [easyEverydayTheme] and
 * [generalKnowledgeTheme] alongside the original [gamesAndTechTheme], picked
 * by CpuDifficulty the same way Hangman picks its word pool (see
 * HangmanGame's KDoc) — a solo puzzle has no opponent to make smarter or
 * dumber, so the clue bank itself is the difficulty lever: EASY draws from
 * short, everyday vocabulary with plain clues; MEDIUM is the original
 * games/tech theme, left byte-for-byte unchanged; HARD draws from longer,
 * general-knowledge trivia answers.
 */
object CrosswordClueBank {
    data class Entry(val word: String, val clue: String)

    val gamesAndTechTheme = listOf(
        Entry("ANDROID", "Google's mobile OS"),
        Entry("KOTLIN", "Language this app is written in"),
        Entry("PIXEL", "Smallest unit of a screen image"),
        Entry("BOARD", "Chess or checkers surface"),
        Entry("DECK", "Collection of playing cards"),
        Entry("DICE", "Rolled for random results"),
        Entry("TOKEN", "Game piece moved on a board"),
        Entry("SCORE", "Tally of points earned"),
        Entry("LEVEL", "Stage of a game"),
        Entry("BONUS", "Extra reward"),
        Entry("TURN", "One player's chance to act"),
        Entry("RULES", "What every game needs"),
        Entry("TILE", "Square piece, as in Scrabble"),
        Entry("MATCH", "A single game session"),
        Entry("TEAM", "Group playing together"),
        Entry("SOLO", "Playing alone"),
        Entry("BOT", "Computer-controlled opponent"),
        Entry("WIN", "Opposite of lose"),
        Entry("DRAW", "Neither side wins"),
        Entry("CARD", "UNO or poker piece"),
        Entry("WILD", "UNO card that changes color"),
        Entry("SKIP", "UNO card that passes the next player"),
        Entry("FOLD", "What a Z-series Samsung phone does"),
        Entry("TABLET", "Larger touchscreen device, like a Tab S9"),
        Entry("APP", "Short for application"),
        Entry("GRID", "Rows and columns layout"),
        Entry("MAZE", "Puzzle you navigate through"),
        Entry("CLUE", "Hint toward an answer"),
        Entry("WORD", "Unit of language, and this game's theme"),
        Entry("PLAY", "To take part in a game"),
        Entry("CONSOLE", "Device used to play video games on a TV"),
        Entry("MONITOR", "Screen you look at while using a computer"),
        Entry("BROWSER", "Software used to view websites, like Chrome"),
        Entry("BATTERY", "Component that stores power for a phone or laptop"),
        Entry("CHARGER", "Cable and adapter used to power up a device"),
        Entry("RESPAWN", "To reappear in a game after being defeated"),
        Entry("FIREWALL", "Security system that blocks unwanted network traffic"),
        Entry("SOFTWARE", "Programs and applications that run on a computer"),
        Entry("HARDWARE", "Physical parts of a computer, like the CPU and RAM"),
        Entry("DOWNLOAD", "To transfer a file from the internet to your device"),
        Entry("PASSWORD", "Secret combination used to log into an account"),
        Entry("USERNAME", "Name you choose to identify your account"),
        Entry("JOYSTICK", "Handheld stick used to control a game character"),
        Entry("KEYBOARD", "Set of keys used to type on a computer"),
        Entry("SPEEDRUN", "Attempt to finish a video game as fast as possible"),
        Entry("BLUETOOTH", "Wireless tech used to connect headphones or controllers"),
        Entry("LAPTOP", "Portable computer that folds shut"),
        Entry("SERVER", "Computer that supplies data to other computers on a network"),
        Entry("UPDATE", "New version of an app installed to fix or improve it"),
        Entry("UPLOAD", "To send a file from your device to the internet"),
        Entry("STREAM", "To watch or listen to content live over the internet"),
        Entry("AVATAR", "Digital character or image that represents a player"),
        Entry("ARCADE", "Venue filled with coin-operated games"),
        Entry("GLITCH", "Unexpected error or bug in a game or program"),
        Entry("CURSOR", "Blinking on-screen marker showing where you'll type or click"),
        Entry("ROUTER", "Device that shares an internet connection with other devices"),
        Entry("IPHONE", "Apple's line of smartphones"),
        Entry("EMOJI", "Small digital icon used to express emotion in a text"),
        Entry("COMBO", "Chained sequence of moves for extra effect in a game"),
        Entry("QUEST", "Mission or objective assigned to a player in a game"),
        Entry("GAMER", "Person who plays video games regularly"),
        Entry("DEBUG", "To find and fix errors in a program"),
        Entry("CACHE", "Temporary storage that speeds up data access"),
        Entry("MODEM", "Device that connects a home network to the internet"),
        Entry("EMAIL", "Message sent electronically over the internet"),
        Entry("ICON", "Small picture that represents an app or file"),
        Entry("CODE", "Set of instructions a computer program follows"),
        Entry("WIFI", "Wireless technology used to connect to the internet"),
        Entry("XBOX", "Microsoft's line of video game consoles")
    )

    /** EASY tier: short, everyday vocabulary with plain, unambiguous clues. */
    val easyEverydayTheme = listOf(
        Entry("CAT", "Common house pet that meows"),
        Entry("DOG", "Common house pet that barks"),
        Entry("SUN", "Star at the center of our solar system"),
        Entry("MOON", "Object that orbits Earth and causes tides"),
        Entry("RAIN", "Water falling from clouds"),
        Entry("TREE", "Tall plant with a trunk and branches"),
        Entry("FISH", "Animal that lives and breathes underwater"),
        Entry("BIRD", "Animal with feathers and wings"),
        Entry("BOOK", "Bound pages you read"),
        Entry("SHOE", "Item worn on your foot"),
        Entry("CAKE", "Sweet baked dessert, often for birthdays"),
        Entry("MILK", "White drink that comes from a cow"),
        Entry("BREAD", "Baked food made mainly from flour"),
        Entry("CHAIR", "Furniture you sit on"),
        Entry("HOUSE", "Building where a family lives"),
        Entry("SMILE", "Facial expression showing happiness"),
        Entry("HAPPY", "Feeling of joy"),
        Entry("WATER", "Clear liquid essential for life"),
        Entry("APPLE", "Round fruit that can be red or green"),
        Entry("BEACH", "Sandy shore next to the ocean"),
        Entry("HAT", "Item worn on top of your head"),
        Entry("CUP", "Small container used for drinking"),
        Entry("PEN", "Tool used to write with ink"),
        Entry("BUS", "Large vehicle that carries many passengers"),
        Entry("CAR", "Vehicle with four wheels used for driving"),
        Entry("BEE", "Buzzing insect that makes honey"),
        Entry("EGG", "Oval food laid by a hen"),
        Entry("ICE", "Frozen form of water"),
        Entry("KEY", "Small metal item used to unlock a door"),
        Entry("BOX", "Container often used for storage or shipping"),
        Entry("COW", "Farm animal that gives milk"),
        Entry("PIG", "Farm animal known for oinking"),
        Entry("HEN", "Female chicken that lays eggs"),
        Entry("OWL", "Nocturnal bird known for hooting"),
        Entry("ANT", "Tiny insect that lives in a colony"),
        Entry("BAT", "Nocturnal flying mammal"),
        Entry("BUG", "Small crawling or flying insect"),
        Entry("JAM", "Sweet fruit spread eaten on toast"),
        Entry("MAP", "Drawing that shows where places are located"),
        Entry("BEAR", "Large wild animal that hibernates in winter"),
        Entry("DUCK", "Bird that swims and quacks"),
        Entry("LION", "Big cat known as the king of the jungle"),
        Entry("FROG", "Amphibian known for jumping and croaking"),
        Entry("CORN", "Yellow vegetable that grows on a cob"),
        Entry("DOOR", "Entryway you open to go into a room"),
        Entry("LAMP", "Device that gives off light on a desk"),
        Entry("SOCK", "Item worn on your foot, under a shoe"),
        Entry("STAR", "Twinkling object seen in the night sky"),
        Entry("SNOW", "Frozen white precipitation that falls in winter"),
        Entry("WIND", "Moving air you feel but cannot see"),
        Entry("BALL", "Round object used in many sports"),
        Entry("GATE", "Movable barrier at an entrance"),
        Entry("LEAF", "Green part of a plant that falls in autumn"),
        Entry("NOSE", "Body part used for smelling"),
        Entry("CLOCK", "Device used to tell the time"),
        Entry("TABLE", "Furniture you eat meals on"),
        Entry("PLATE", "Flat dish you put food on"),
        Entry("GRAPE", "Small round fruit that grows in bunches"),
        Entry("LEMON", "Sour yellow citrus fruit"),
        Entry("PEACH", "Fuzzy-skinned orange fruit with a pit"),
        Entry("BERRY", "Small, juicy fruit, such as a strawberry"),
        Entry("HONEY", "Sweet substance made by bees"),
        Entry("CANDY", "Sweet treat, often eaten as a snack"),
        Entry("PIZZA", "Round baked dish topped with cheese and sauce"),
        Entry("CLOUD", "Fluffy white shape floating in the sky"),
        Entry("RIVER", "Flowing body of fresh water"),
        Entry("OCEAN", "Vast body of salt water"),
        Entry("FIELD", "Open area covered in grass or crops"),
        Entry("PUPPY", "Baby dog"),
        Entry("SHARK", "Large ocean predator known for sharp teeth"),
        Entry("STORM", "Weather event with strong wind and heavy rain"),
        Entry("BRAIN", "Organ in your head used for thinking"),
        Entry("HEART", "Organ that pumps blood through your body")
    )

    /**
     * HARD tier: longer general-knowledge trivia. Every clue below was
     * checked to be factually correct with exactly one reasonable
     * single-word answer (no ties, no multi-word answers).
     */
    val generalKnowledgeTheme = listOf(
        Entry("PARIS", "Capital city of France"),
        Entry("TOKYO", "Capital city of Japan"),
        Entry("NILE", "Longest river in Africa"),
        Entry("EVEREST", "Tallest mountain above sea level"),
        Entry("MERCURY", "Closest planet to the Sun"),
        Entry("SATURN", "Planet famous for its rings"),
        Entry("OXYGEN", "Gas humans need to breathe"),
        Entry("GRAVITY", "Force that pulls objects toward Earth"),
        Entry("GALAXY", "Huge system of stars, such as the Milky Way"),
        Entry("COMET", "Icy object that grows a tail near the Sun"),
        Entry("PLANET", "A body like Earth or Mars that orbits a star"),
        Entry("ASTEROID", "Rocky body orbiting the Sun, smaller than a planet"),
        Entry("METEOR", "Streak of light from a space rock burning up in the sky"),
        Entry("TELESCOPE", "Instrument used to observe distant stars and planets"),
        Entry("VOLCANO", "Mountain that can erupt with lava"),
        Entry("GLACIER", "Massive, slow-moving river of ice"),
        Entry("CANYON", "Deep gorge carved by a river, like the Grand one"),
        Entry("DESERT", "Dry region that receives very little rainfall"),
        Entry("EQUATOR", "Imaginary line dividing Earth into two hemispheres"),
        Entry("CONTINENT", "Large landmass, one of seven on Earth"),
        Entry("PENGUIN", "Flightless bird found in Antarctica"),
        Entry("GIRAFFE", "Tallest land animal, known for its long neck"),
        Entry("CHEETAH", "Fastest land animal"),
        Entry("DOLPHIN", "Intelligent marine mammal known for clicking sounds"),
        Entry("EINSTEIN", "Physicist who developed the theory of relativity"),
        Entry("DARWIN", "Naturalist known for the theory of evolution"),
        Entry("SHAKESPEARE", "Playwright who wrote Romeo and Juliet"),
        Entry("PYRAMID", "Ancient Egyptian structure built as a royal tomb"),
        Entry("DEMOCRACY", "System of government where citizens vote for leaders"),
        Entry("PRESIDENT", "Head of state in a republic such as the U.S."),
        Entry("LIBRARY", "Building full of books available to borrow"),
        // 9-letter answers: this length band (along with 10/11/12 below) is
        // deliberately large. See pickSeed()/SEED_LENGTH_TOLERANCE in
        // CrosswordGame.kt — the HARD tier's anchor word is chosen from
        // words within 2 letters of the theme's longest entry, and this
        // theme used to have only 5 words that long (a guaranteed repeat
        // once the seed history filled up). The longest words are now the
        // 12-letter group further below, so the qualifying window covers
        // every 10/11/12-letter entry — nearly 30 candidates.
        Entry("AVALANCHE", "Sudden fall of snow and ice down a mountainside"),
        Entry("HURRICANE", "Powerful storm that forms over the Atlantic Ocean, with a calm eye at its center"),
        Entry("CROCODILE", "Long-snouted reptile found in rivers across Africa, Asia, and Australia"),
        Entry("ORANGUTAN", "Red-haired great ape native to the rainforests of Borneo and Sumatra"),
        Entry("AUSTRALIA", "Continent and country famous for kangaroos"),
        Entry("ARGENTINA", "South American country where tango dancing originated"),
        Entry("INDONESIA", "Southeast Asian island nation with the world's largest Muslim population"),
        Entry("SINGAPORE", "Island city-state in Southeast Asia"),
        Entry("ECOSYSTEM", "Community of living things interacting with their environment"),
        Entry("EVOLUTION", "Gradual change in species over generations, as described by Darwin"),
        Entry("ASTRONOMY", "Scientific study of stars, planets, and outer space"),
        Entry("CHEMISTRY", "Branch of science that studies matter and how it reacts"),
        Entry("GEOGRAPHY", "Study of Earth's physical features, climates, and countries"),
        Entry("ARCHITECT", "Professional who designs buildings"),
        Entry("SCULPTURE", "Three-dimensional art form created by carving, molding, or casting"),
        Entry("ORCHESTRA", "Large group of classical musicians led by a conductor"),
        Entry("BEETHOVEN", "Composer who kept writing symphonies after losing his hearing"),
        Entry("REMBRANDT", "Dutch painter famous for The Night Watch"),
        Entry("COLOSSEUM", "Ancient Roman amphitheater used for gladiator contests"),
        Entry("PARTHENON", "Ancient Greek temple on the Acropolis in Athens"),
        Entry("CLEOPATRA", "Famed queen of ancient Egypt allied with Julius Caesar"),
        Entry("JEFFERSON", "Third U.S. president and principal author of the Declaration of Independence"),
        Entry("ROOSEVELT", "Surname shared by two U.S. presidents, Theodore and Franklin"),
        Entry("CATHEDRAL", "Large, important church that serves as a bishop's seat"),
        Entry("MONASTERY", "Place where a community of monks lives and worships"),
        Entry("BUTTERFLY", "Insect that hatches from a caterpillar and later emerges from a chrysalis"),
        Entry("PENINSULA", "Piece of land surrounded by water on three sides"),
        // 10-letter answers.
        Entry("CHIMPANZEE", "Great ape studied extensively by primatologist Jane Goodall"),
        Entry("ANTARCTICA", "Icy continent surrounding the South Pole"),
        Entry("CALIFORNIA", "Most populous U.S. state, home to Hollywood"),
        Entry("WASHINGTON", "Surname of the first president of the United States"),
        Entry("ATMOSPHERE", "Layer of gases surrounding a planet like Earth"),
        Entry("MICROSCOPE", "Instrument used to magnify very small objects"),
        Entry("REVOLUTION", "Widespread uprising that dramatically changes a nation's government"),
        Entry("PARLIAMENT", "Legislative assembly, as found in the United Kingdom"),
        Entry("RHINOCEROS", "Large animal with one or two horns on its snout"),
        Entry("STALACTITE", "Icicle-shaped mineral formation hanging from a cave ceiling"),
        Entry("STALAGMITE", "Mineral formation that rises up from a cave floor"),
        Entry("EARTHQUAKE", "Sudden shaking of the ground caused by shifting tectonic plates"),
        Entry("LIGHTHOUSE", "Tower with a beacon that guides ships safely to shore"),
        Entry("RAINFOREST", "Dense, tropical forest with heavy year-round rainfall, like the Amazon"),
        Entry("HEMISPHERE", "Half of the Earth, such as the Northern or Southern"),
        // 11-letter answers.
        Entry("ELECTRICITY", "Form of energy that powers lights and appliances"),
        Entry("YELLOWSTONE", "First national park in the world, home to Old Faithful"),
        Entry("MISSISSIPPI", "U.S. river flowing from Minnesota to the Gulf of Mexico"),
        Entry("STETHOSCOPE", "Instrument doctors use to listen to your heartbeat"),
        Entry("MESOPOTAMIA", "Ancient region between the Tigris and Euphrates rivers"),
        Entry("SARCOPHAGUS", "Stone coffin used for burials in ancient Egypt"),
        Entry("CATERPILLAR", "Larval stage of a butterfly or moth"),
        Entry("ARCHIPELAGO", "Group or chain of islands"),
        // 12-letter answers — the new longest words in this theme.
        Entry("CONSTITUTION", "Document that lays out a nation's fundamental laws"),
        Entry("INDEPENDENCE", "Freedom from outside control, declared by the U.S. in 1776"),
        Entry("CIVILIZATION", "Advanced, organized society, such as ancient Rome"),
        Entry("HIPPOPOTAMUS", "Large African mammal that spends much of its time in rivers"),
        Entry("THUNDERSTORM", "Storm featuring thunder, lightning, and heavy rain")
    )
}
